language: python
sudo: required
dist: xenial
python:
  - '3.7'
env:
  global:
    - COMMENT_EXTRACTION=comment-extraction-master
    - EXTRACTED_DIR=docs/extracted-comments
    - INPUT_DIR=src
    - LANGUAGE=java
    - ROOT_URL=https://github.com/Fantom-Foundation/jlachesis
before_install:
  - curl -L https://github.com/dev10/comment-extraction/archive/master.tar.gz -o comment-extraction.tgz
  - tar xf comment-extraction.tgz
install:
  - pip install -r $COMMENT_EXTRACTION/requirements.txt
script:
  - >
    python $COMMENT_EXTRACTION/antlr.py
    -l $LANGUAGE
    -o $EXTRACTED_DIR
    -ct $TRAVIS_COMMIT
    -ru $ROOT_URL
    -d $INPUT_DIR
after_success:
  - cd docs/
  - pip install -r requirements.txt
  - make html
  - "./deploy.sh"