// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: poset/proto/block.proto

package poset.proto;

public final class PBlock {
  private PBlock() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BlockBodyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:poset.proto.BlockBody)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int64 Index = 1;</code>
     */
    long getIndex();

    /**
     * <code>optional int64 RoundReceived = 2;</code>
     */
    long getRoundReceived();

    /**
     * <code>repeated bytes Transactions = 5;</code>
     */
    java.util.List<com.google.protobuf.ByteString> getTransactionsList();
    /**
     * <code>repeated bytes Transactions = 5;</code>
     */
    int getTransactionsCount();
    /**
     * <code>repeated bytes Transactions = 5;</code>
     */
    com.google.protobuf.ByteString getTransactions(int index);
  }
  /**
   * Protobuf type {@code poset.proto.BlockBody}
   */
  public  static final class BlockBody extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:poset.proto.BlockBody)
      BlockBodyOrBuilder {
    // Use BlockBody.newBuilder() to construct.
    private BlockBody(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BlockBody() {
      index_ = 0L;
      roundReceived_ = 0L;
      transactions_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private BlockBody(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              index_ = input.readInt64();
              break;
            }
            case 16: {

              roundReceived_ = input.readInt64();
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                transactions_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
                mutable_bitField0_ |= 0x00000004;
              }
              transactions_.add(input.readBytes());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          transactions_ = java.util.Collections.unmodifiableList(transactions_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return poset.proto.PBlock.internal_static_poset_proto_BlockBody_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return poset.proto.PBlock.internal_static_poset_proto_BlockBody_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              poset.proto.PBlock.BlockBody.class, poset.proto.PBlock.BlockBody.Builder.class);
    }

    private int bitField0_;
    public static final int INDEX_FIELD_NUMBER = 1;
    private long index_;
    /**
     * <code>optional int64 Index = 1;</code>
     */
    public long getIndex() {
      return index_;
    }

    public static final int ROUNDRECEIVED_FIELD_NUMBER = 2;
    private long roundReceived_;
    /**
     * <code>optional int64 RoundReceived = 2;</code>
     */
    public long getRoundReceived() {
      return roundReceived_;
    }

    public static final int TRANSACTIONS_FIELD_NUMBER = 5;
    private java.util.List<com.google.protobuf.ByteString> transactions_;
    /**
     * <code>repeated bytes Transactions = 5;</code>
     */
    public java.util.List<com.google.protobuf.ByteString>
        getTransactionsList() {
      return transactions_;
    }
    /**
     * <code>repeated bytes Transactions = 5;</code>
     */
    public int getTransactionsCount() {
      return transactions_.size();
    }
    /**
     * <code>repeated bytes Transactions = 5;</code>
     */
    public com.google.protobuf.ByteString getTransactions(int index) {
      return transactions_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (index_ != 0L) {
        output.writeInt64(1, index_);
      }
      if (roundReceived_ != 0L) {
        output.writeInt64(2, roundReceived_);
      }
      for (int i = 0; i < transactions_.size(); i++) {
        output.writeBytes(5, transactions_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (index_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, index_);
      }
      if (roundReceived_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, roundReceived_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < transactions_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(transactions_.get(i));
        }
        size += dataSize;
        size += 1 * getTransactionsList().size();
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof poset.proto.PBlock.BlockBody)) {
        return super.equals(obj);
      }
      poset.proto.PBlock.BlockBody other = (poset.proto.PBlock.BlockBody) obj;

      boolean result = true;
      result = result && (getIndex()
          == other.getIndex());
      result = result && (getRoundReceived()
          == other.getRoundReceived());
      result = result && getTransactionsList()
          .equals(other.getTransactionsList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + INDEX_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getIndex());
      hash = (37 * hash) + ROUNDRECEIVED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getRoundReceived());
      if (getTransactionsCount() > 0) {
        hash = (37 * hash) + TRANSACTIONS_FIELD_NUMBER;
        hash = (53 * hash) + getTransactionsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static poset.proto.PBlock.BlockBody parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static poset.proto.PBlock.BlockBody parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static poset.proto.PBlock.BlockBody parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static poset.proto.PBlock.BlockBody parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static poset.proto.PBlock.BlockBody parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static poset.proto.PBlock.BlockBody parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static poset.proto.PBlock.BlockBody parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static poset.proto.PBlock.BlockBody parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static poset.proto.PBlock.BlockBody parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static poset.proto.PBlock.BlockBody parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(poset.proto.PBlock.BlockBody prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code poset.proto.BlockBody}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:poset.proto.BlockBody)
        poset.proto.PBlock.BlockBodyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return poset.proto.PBlock.internal_static_poset_proto_BlockBody_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return poset.proto.PBlock.internal_static_poset_proto_BlockBody_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                poset.proto.PBlock.BlockBody.class, poset.proto.PBlock.BlockBody.Builder.class);
      }

      // Construct using poset.proto.PBlock.BlockBody.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        index_ = 0L;

        roundReceived_ = 0L;

        transactions_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return poset.proto.PBlock.internal_static_poset_proto_BlockBody_descriptor;
      }

      public poset.proto.PBlock.BlockBody getDefaultInstanceForType() {
        return poset.proto.PBlock.BlockBody.getDefaultInstance();
      }

      public poset.proto.PBlock.BlockBody build() {
        poset.proto.PBlock.BlockBody result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public poset.proto.PBlock.BlockBody buildPartial() {
        poset.proto.PBlock.BlockBody result = new poset.proto.PBlock.BlockBody(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.index_ = index_;
        result.roundReceived_ = roundReceived_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          transactions_ = java.util.Collections.unmodifiableList(transactions_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.transactions_ = transactions_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof poset.proto.PBlock.BlockBody) {
          return mergeFrom((poset.proto.PBlock.BlockBody)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(poset.proto.PBlock.BlockBody other) {
        if (other == poset.proto.PBlock.BlockBody.getDefaultInstance()) return this;
        if (other.getIndex() != 0L) {
          setIndex(other.getIndex());
        }
        if (other.getRoundReceived() != 0L) {
          setRoundReceived(other.getRoundReceived());
        }
        if (!other.transactions_.isEmpty()) {
          if (transactions_.isEmpty()) {
            transactions_ = other.transactions_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureTransactionsIsMutable();
            transactions_.addAll(other.transactions_);
          }
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        poset.proto.PBlock.BlockBody parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (poset.proto.PBlock.BlockBody) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long index_ ;
      /**
       * <code>optional int64 Index = 1;</code>
       */
      public long getIndex() {
        return index_;
      }
      /**
       * <code>optional int64 Index = 1;</code>
       */
      public Builder setIndex(long value) {
        
        index_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 Index = 1;</code>
       */
      public Builder clearIndex() {
        
        index_ = 0L;
        onChanged();
        return this;
      }

      private long roundReceived_ ;
      /**
       * <code>optional int64 RoundReceived = 2;</code>
       */
      public long getRoundReceived() {
        return roundReceived_;
      }
      /**
       * <code>optional int64 RoundReceived = 2;</code>
       */
      public Builder setRoundReceived(long value) {
        
        roundReceived_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 RoundReceived = 2;</code>
       */
      public Builder clearRoundReceived() {
        
        roundReceived_ = 0L;
        onChanged();
        return this;
      }

      private java.util.List<com.google.protobuf.ByteString> transactions_ = java.util.Collections.emptyList();
      private void ensureTransactionsIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          transactions_ = new java.util.ArrayList<com.google.protobuf.ByteString>(transactions_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated bytes Transactions = 5;</code>
       */
      public java.util.List<com.google.protobuf.ByteString>
          getTransactionsList() {
        return java.util.Collections.unmodifiableList(transactions_);
      }
      /**
       * <code>repeated bytes Transactions = 5;</code>
       */
      public int getTransactionsCount() {
        return transactions_.size();
      }
      /**
       * <code>repeated bytes Transactions = 5;</code>
       */
      public com.google.protobuf.ByteString getTransactions(int index) {
        return transactions_.get(index);
      }
      /**
       * <code>repeated bytes Transactions = 5;</code>
       */
      public Builder setTransactions(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureTransactionsIsMutable();
        transactions_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes Transactions = 5;</code>
       */
      public Builder addTransactions(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureTransactionsIsMutable();
        transactions_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes Transactions = 5;</code>
       */
      public Builder addAllTransactions(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        ensureTransactionsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, transactions_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes Transactions = 5;</code>
       */
      public Builder clearTransactions() {
        transactions_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:poset.proto.BlockBody)
    }

    // @@protoc_insertion_point(class_scope:poset.proto.BlockBody)
    private static final poset.proto.PBlock.BlockBody DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new poset.proto.PBlock.BlockBody();
    }

    public static poset.proto.PBlock.BlockBody getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BlockBody>
        PARSER = new com.google.protobuf.AbstractParser<BlockBody>() {
      public BlockBody parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new BlockBody(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BlockBody> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BlockBody> getParserForType() {
      return PARSER;
    }

    public poset.proto.PBlock.BlockBody getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface WireBlockSignatureOrBuilder extends
      // @@protoc_insertion_point(interface_extends:poset.proto.WireBlockSignature)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int64 Index = 1;</code>
     */
    long getIndex();

    /**
     * <code>optional string Signature = 2;</code>
     */
    java.lang.String getSignature();
    /**
     * <code>optional string Signature = 2;</code>
     */
    com.google.protobuf.ByteString
        getSignatureBytes();
  }
  /**
   * Protobuf type {@code poset.proto.WireBlockSignature}
   */
  public  static final class WireBlockSignature extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:poset.proto.WireBlockSignature)
      WireBlockSignatureOrBuilder {
    // Use WireBlockSignature.newBuilder() to construct.
    private WireBlockSignature(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private WireBlockSignature() {
      index_ = 0L;
      signature_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private WireBlockSignature(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              index_ = input.readInt64();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              signature_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return poset.proto.PBlock.internal_static_poset_proto_WireBlockSignature_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return poset.proto.PBlock.internal_static_poset_proto_WireBlockSignature_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              poset.proto.PBlock.WireBlockSignature.class, poset.proto.PBlock.WireBlockSignature.Builder.class);
    }

    public static final int INDEX_FIELD_NUMBER = 1;
    private long index_;
    /**
     * <code>optional int64 Index = 1;</code>
     */
    public long getIndex() {
      return index_;
    }

    public static final int SIGNATURE_FIELD_NUMBER = 2;
    private volatile java.lang.Object signature_;
    /**
     * <code>optional string Signature = 2;</code>
     */
    public java.lang.String getSignature() {
      java.lang.Object ref = signature_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        signature_ = s;
        return s;
      }
    }
    /**
     * <code>optional string Signature = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSignatureBytes() {
      java.lang.Object ref = signature_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        signature_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (index_ != 0L) {
        output.writeInt64(1, index_);
      }
      if (!getSignatureBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, signature_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (index_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, index_);
      }
      if (!getSignatureBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, signature_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof poset.proto.PBlock.WireBlockSignature)) {
        return super.equals(obj);
      }
      poset.proto.PBlock.WireBlockSignature other = (poset.proto.PBlock.WireBlockSignature) obj;

      boolean result = true;
      result = result && (getIndex()
          == other.getIndex());
      result = result && getSignature()
          .equals(other.getSignature());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + INDEX_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getIndex());
      hash = (37 * hash) + SIGNATURE_FIELD_NUMBER;
      hash = (53 * hash) + getSignature().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static poset.proto.PBlock.WireBlockSignature parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static poset.proto.PBlock.WireBlockSignature parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static poset.proto.PBlock.WireBlockSignature parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static poset.proto.PBlock.WireBlockSignature parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static poset.proto.PBlock.WireBlockSignature parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static poset.proto.PBlock.WireBlockSignature parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static poset.proto.PBlock.WireBlockSignature parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static poset.proto.PBlock.WireBlockSignature parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static poset.proto.PBlock.WireBlockSignature parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static poset.proto.PBlock.WireBlockSignature parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(poset.proto.PBlock.WireBlockSignature prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code poset.proto.WireBlockSignature}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:poset.proto.WireBlockSignature)
        poset.proto.PBlock.WireBlockSignatureOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return poset.proto.PBlock.internal_static_poset_proto_WireBlockSignature_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return poset.proto.PBlock.internal_static_poset_proto_WireBlockSignature_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                poset.proto.PBlock.WireBlockSignature.class, poset.proto.PBlock.WireBlockSignature.Builder.class);
      }

      // Construct using poset.proto.PBlock.WireBlockSignature.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        index_ = 0L;

        signature_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return poset.proto.PBlock.internal_static_poset_proto_WireBlockSignature_descriptor;
      }

      public poset.proto.PBlock.WireBlockSignature getDefaultInstanceForType() {
        return poset.proto.PBlock.WireBlockSignature.getDefaultInstance();
      }

      public poset.proto.PBlock.WireBlockSignature build() {
        poset.proto.PBlock.WireBlockSignature result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public poset.proto.PBlock.WireBlockSignature buildPartial() {
        poset.proto.PBlock.WireBlockSignature result = new poset.proto.PBlock.WireBlockSignature(this);
        result.index_ = index_;
        result.signature_ = signature_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof poset.proto.PBlock.WireBlockSignature) {
          return mergeFrom((poset.proto.PBlock.WireBlockSignature)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(poset.proto.PBlock.WireBlockSignature other) {
        if (other == poset.proto.PBlock.WireBlockSignature.getDefaultInstance()) return this;
        if (other.getIndex() != 0L) {
          setIndex(other.getIndex());
        }
        if (!other.getSignature().isEmpty()) {
          signature_ = other.signature_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        poset.proto.PBlock.WireBlockSignature parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (poset.proto.PBlock.WireBlockSignature) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long index_ ;
      /**
       * <code>optional int64 Index = 1;</code>
       */
      public long getIndex() {
        return index_;
      }
      /**
       * <code>optional int64 Index = 1;</code>
       */
      public Builder setIndex(long value) {
        
        index_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 Index = 1;</code>
       */
      public Builder clearIndex() {
        
        index_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object signature_ = "";
      /**
       * <code>optional string Signature = 2;</code>
       */
      public java.lang.String getSignature() {
        java.lang.Object ref = signature_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          signature_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string Signature = 2;</code>
       */
      public com.google.protobuf.ByteString
          getSignatureBytes() {
        java.lang.Object ref = signature_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          signature_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string Signature = 2;</code>
       */
      public Builder setSignature(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        signature_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string Signature = 2;</code>
       */
      public Builder clearSignature() {
        
        signature_ = getDefaultInstance().getSignature();
        onChanged();
        return this;
      }
      /**
       * <code>optional string Signature = 2;</code>
       */
      public Builder setSignatureBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        signature_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:poset.proto.WireBlockSignature)
    }

    // @@protoc_insertion_point(class_scope:poset.proto.WireBlockSignature)
    private static final poset.proto.PBlock.WireBlockSignature DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new poset.proto.PBlock.WireBlockSignature();
    }

    public static poset.proto.PBlock.WireBlockSignature getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<WireBlockSignature>
        PARSER = new com.google.protobuf.AbstractParser<WireBlockSignature>() {
      public WireBlockSignature parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new WireBlockSignature(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<WireBlockSignature> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<WireBlockSignature> getParserForType() {
      return PARSER;
    }

    public poset.proto.PBlock.WireBlockSignature getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface BlockOrBuilder extends
      // @@protoc_insertion_point(interface_extends:poset.proto.Block)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .poset.proto.BlockBody Body = 1;</code>
     */
    boolean hasBody();
    /**
     * <code>optional .poset.proto.BlockBody Body = 1;</code>
     */
    poset.proto.PBlock.BlockBody getBody();
    /**
     * <code>optional .poset.proto.BlockBody Body = 1;</code>
     */
    poset.proto.PBlock.BlockBodyOrBuilder getBodyOrBuilder();

    /**
     * <code>map&lt;string, string&gt; Signatures = 2;</code>
     */
    int getSignaturesCount();
    /**
     * <code>map&lt;string, string&gt; Signatures = 2;</code>
     */
    boolean containsSignatures(
        java.lang.String key);
    /**
     * Use {@link #getSignaturesMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.String>
    getSignatures();
    /**
     * <code>map&lt;string, string&gt; Signatures = 2;</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getSignaturesMap();
    /**
     * <code>map&lt;string, string&gt; Signatures = 2;</code>
     */

    java.lang.String getSignaturesOrDefault(
        java.lang.String key,
        java.lang.String defaultValue);
    /**
     * <code>map&lt;string, string&gt; Signatures = 2;</code>
     */

    java.lang.String getSignaturesOrThrow(
        java.lang.String key);

    /**
     * <code>optional bytes hash = 3;</code>
     */
    com.google.protobuf.ByteString getHash();

    /**
     * <code>optional string hex = 4;</code>
     */
    java.lang.String getHex();
    /**
     * <code>optional string hex = 4;</code>
     */
    com.google.protobuf.ByteString
        getHexBytes();

    /**
     * <code>optional bytes StateHash = 5;</code>
     */
    com.google.protobuf.ByteString getStateHash();

    /**
     * <code>optional bytes FrameHash = 6;</code>
     */
    com.google.protobuf.ByteString getFrameHash();
  }
  /**
   * Protobuf type {@code poset.proto.Block}
   */
  public  static final class Block extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:poset.proto.Block)
      BlockOrBuilder {
    // Use Block.newBuilder() to construct.
    private Block(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Block() {
      hash_ = com.google.protobuf.ByteString.EMPTY;
      hex_ = "";
      stateHash_ = com.google.protobuf.ByteString.EMPTY;
      frameHash_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Block(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              poset.proto.PBlock.BlockBody.Builder subBuilder = null;
              if (body_ != null) {
                subBuilder = body_.toBuilder();
              }
              body_ = input.readMessage(poset.proto.PBlock.BlockBody.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(body_);
                body_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                signatures_ = com.google.protobuf.MapField.newMapField(
                    SignaturesDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000002;
              }
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              signatures = input.readMessage(
                  SignaturesDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              signatures_.getMutableMap().put(signatures.getKey(), signatures.getValue());
              break;
            }
            case 26: {

              hash_ = input.readBytes();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              hex_ = s;
              break;
            }
            case 42: {

              stateHash_ = input.readBytes();
              break;
            }
            case 50: {

              frameHash_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return poset.proto.PBlock.internal_static_poset_proto_Block_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 2:
          return internalGetSignatures();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return poset.proto.PBlock.internal_static_poset_proto_Block_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              poset.proto.PBlock.Block.class, poset.proto.PBlock.Block.Builder.class);
    }

    private int bitField0_;
    public static final int BODY_FIELD_NUMBER = 1;
    private poset.proto.PBlock.BlockBody body_;
    /**
     * <code>optional .poset.proto.BlockBody Body = 1;</code>
     */
    public boolean hasBody() {
      return body_ != null;
    }
    /**
     * <code>optional .poset.proto.BlockBody Body = 1;</code>
     */
    public poset.proto.PBlock.BlockBody getBody() {
      return body_ == null ? poset.proto.PBlock.BlockBody.getDefaultInstance() : body_;
    }
    /**
     * <code>optional .poset.proto.BlockBody Body = 1;</code>
     */
    public poset.proto.PBlock.BlockBodyOrBuilder getBodyOrBuilder() {
      return getBody();
    }

    public static final int SIGNATURES_FIELD_NUMBER = 2;
    private static final class SignaturesDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.String>newDefaultInstance(
                  poset.proto.PBlock.internal_static_poset_proto_Block_SignaturesEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> signatures_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetSignatures() {
      if (signatures_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            SignaturesDefaultEntryHolder.defaultEntry);
      }
      return signatures_;
    }

    public int getSignaturesCount() {
      return internalGetSignatures().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; Signatures = 2;</code>
     */

    public boolean containsSignatures(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetSignatures().getMap().containsKey(key);
    }
    /**
     * Use {@link #getSignaturesMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getSignatures() {
      return getSignaturesMap();
    }
    /**
     * <code>map&lt;string, string&gt; Signatures = 2;</code>
     */

    public java.util.Map<java.lang.String, java.lang.String> getSignaturesMap() {
      return internalGetSignatures().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; Signatures = 2;</code>
     */

    public java.lang.String getSignaturesOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetSignatures().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; Signatures = 2;</code>
     */

    public java.lang.String getSignaturesOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetSignatures().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public static final int HASH_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString hash_;
    /**
     * <code>optional bytes hash = 3;</code>
     */
    public com.google.protobuf.ByteString getHash() {
      return hash_;
    }

    public static final int HEX_FIELD_NUMBER = 4;
    private volatile java.lang.Object hex_;
    /**
     * <code>optional string hex = 4;</code>
     */
    public java.lang.String getHex() {
      java.lang.Object ref = hex_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        hex_ = s;
        return s;
      }
    }
    /**
     * <code>optional string hex = 4;</code>
     */
    public com.google.protobuf.ByteString
        getHexBytes() {
      java.lang.Object ref = hex_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        hex_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STATEHASH_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString stateHash_;
    /**
     * <code>optional bytes StateHash = 5;</code>
     */
    public com.google.protobuf.ByteString getStateHash() {
      return stateHash_;
    }

    public static final int FRAMEHASH_FIELD_NUMBER = 6;
    private com.google.protobuf.ByteString frameHash_;
    /**
     * <code>optional bytes FrameHash = 6;</code>
     */
    public com.google.protobuf.ByteString getFrameHash() {
      return frameHash_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (body_ != null) {
        output.writeMessage(1, getBody());
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetSignatures().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        signatures = SignaturesDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        output.writeMessage(2, signatures);
      }
      if (!hash_.isEmpty()) {
        output.writeBytes(3, hash_);
      }
      if (!getHexBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, hex_);
      }
      if (!stateHash_.isEmpty()) {
        output.writeBytes(5, stateHash_);
      }
      if (!frameHash_.isEmpty()) {
        output.writeBytes(6, frameHash_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (body_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getBody());
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetSignatures().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        signatures = SignaturesDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(2, signatures);
      }
      if (!hash_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, hash_);
      }
      if (!getHexBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, hex_);
      }
      if (!stateHash_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, stateHash_);
      }
      if (!frameHash_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, frameHash_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof poset.proto.PBlock.Block)) {
        return super.equals(obj);
      }
      poset.proto.PBlock.Block other = (poset.proto.PBlock.Block) obj;

      boolean result = true;
      result = result && (hasBody() == other.hasBody());
      if (hasBody()) {
        result = result && getBody()
            .equals(other.getBody());
      }
      result = result && internalGetSignatures().equals(
          other.internalGetSignatures());
      result = result && getHash()
          .equals(other.getHash());
      result = result && getHex()
          .equals(other.getHex());
      result = result && getStateHash()
          .equals(other.getStateHash());
      result = result && getFrameHash()
          .equals(other.getFrameHash());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasBody()) {
        hash = (37 * hash) + BODY_FIELD_NUMBER;
        hash = (53 * hash) + getBody().hashCode();
      }
      if (!internalGetSignatures().getMap().isEmpty()) {
        hash = (37 * hash) + SIGNATURES_FIELD_NUMBER;
        hash = (53 * hash) + internalGetSignatures().hashCode();
      }
      hash = (37 * hash) + HASH_FIELD_NUMBER;
      hash = (53 * hash) + getHash().hashCode();
      hash = (37 * hash) + HEX_FIELD_NUMBER;
      hash = (53 * hash) + getHex().hashCode();
      hash = (37 * hash) + STATEHASH_FIELD_NUMBER;
      hash = (53 * hash) + getStateHash().hashCode();
      hash = (37 * hash) + FRAMEHASH_FIELD_NUMBER;
      hash = (53 * hash) + getFrameHash().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static poset.proto.PBlock.Block parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static poset.proto.PBlock.Block parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static poset.proto.PBlock.Block parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static poset.proto.PBlock.Block parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static poset.proto.PBlock.Block parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static poset.proto.PBlock.Block parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static poset.proto.PBlock.Block parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static poset.proto.PBlock.Block parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static poset.proto.PBlock.Block parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static poset.proto.PBlock.Block parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(poset.proto.PBlock.Block prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code poset.proto.Block}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:poset.proto.Block)
        poset.proto.PBlock.BlockOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return poset.proto.PBlock.internal_static_poset_proto_Block_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 2:
            return internalGetSignatures();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 2:
            return internalGetMutableSignatures();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return poset.proto.PBlock.internal_static_poset_proto_Block_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                poset.proto.PBlock.Block.class, poset.proto.PBlock.Block.Builder.class);
      }

      // Construct using poset.proto.PBlock.Block.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (bodyBuilder_ == null) {
          body_ = null;
        } else {
          body_ = null;
          bodyBuilder_ = null;
        }
        internalGetMutableSignatures().clear();
        hash_ = com.google.protobuf.ByteString.EMPTY;

        hex_ = "";

        stateHash_ = com.google.protobuf.ByteString.EMPTY;

        frameHash_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return poset.proto.PBlock.internal_static_poset_proto_Block_descriptor;
      }

      public poset.proto.PBlock.Block getDefaultInstanceForType() {
        return poset.proto.PBlock.Block.getDefaultInstance();
      }

      public poset.proto.PBlock.Block build() {
        poset.proto.PBlock.Block result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public poset.proto.PBlock.Block buildPartial() {
        poset.proto.PBlock.Block result = new poset.proto.PBlock.Block(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (bodyBuilder_ == null) {
          result.body_ = body_;
        } else {
          result.body_ = bodyBuilder_.build();
        }
        result.signatures_ = internalGetSignatures();
        result.signatures_.makeImmutable();
        result.hash_ = hash_;
        result.hex_ = hex_;
        result.stateHash_ = stateHash_;
        result.frameHash_ = frameHash_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof poset.proto.PBlock.Block) {
          return mergeFrom((poset.proto.PBlock.Block)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(poset.proto.PBlock.Block other) {
        if (other == poset.proto.PBlock.Block.getDefaultInstance()) return this;
        if (other.hasBody()) {
          mergeBody(other.getBody());
        }
        internalGetMutableSignatures().mergeFrom(
            other.internalGetSignatures());
        if (other.getHash() != com.google.protobuf.ByteString.EMPTY) {
          setHash(other.getHash());
        }
        if (!other.getHex().isEmpty()) {
          hex_ = other.hex_;
          onChanged();
        }
        if (other.getStateHash() != com.google.protobuf.ByteString.EMPTY) {
          setStateHash(other.getStateHash());
        }
        if (other.getFrameHash() != com.google.protobuf.ByteString.EMPTY) {
          setFrameHash(other.getFrameHash());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        poset.proto.PBlock.Block parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (poset.proto.PBlock.Block) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private poset.proto.PBlock.BlockBody body_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          poset.proto.PBlock.BlockBody, poset.proto.PBlock.BlockBody.Builder, poset.proto.PBlock.BlockBodyOrBuilder> bodyBuilder_;
      /**
       * <code>optional .poset.proto.BlockBody Body = 1;</code>
       */
      public boolean hasBody() {
        return bodyBuilder_ != null || body_ != null;
      }
      /**
       * <code>optional .poset.proto.BlockBody Body = 1;</code>
       */
      public poset.proto.PBlock.BlockBody getBody() {
        if (bodyBuilder_ == null) {
          return body_ == null ? poset.proto.PBlock.BlockBody.getDefaultInstance() : body_;
        } else {
          return bodyBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .poset.proto.BlockBody Body = 1;</code>
       */
      public Builder setBody(poset.proto.PBlock.BlockBody value) {
        if (bodyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          body_ = value;
          onChanged();
        } else {
          bodyBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .poset.proto.BlockBody Body = 1;</code>
       */
      public Builder setBody(
          poset.proto.PBlock.BlockBody.Builder builderForValue) {
        if (bodyBuilder_ == null) {
          body_ = builderForValue.build();
          onChanged();
        } else {
          bodyBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .poset.proto.BlockBody Body = 1;</code>
       */
      public Builder mergeBody(poset.proto.PBlock.BlockBody value) {
        if (bodyBuilder_ == null) {
          if (body_ != null) {
            body_ =
              poset.proto.PBlock.BlockBody.newBuilder(body_).mergeFrom(value).buildPartial();
          } else {
            body_ = value;
          }
          onChanged();
        } else {
          bodyBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .poset.proto.BlockBody Body = 1;</code>
       */
      public Builder clearBody() {
        if (bodyBuilder_ == null) {
          body_ = null;
          onChanged();
        } else {
          body_ = null;
          bodyBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .poset.proto.BlockBody Body = 1;</code>
       */
      public poset.proto.PBlock.BlockBody.Builder getBodyBuilder() {
        
        onChanged();
        return getBodyFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .poset.proto.BlockBody Body = 1;</code>
       */
      public poset.proto.PBlock.BlockBodyOrBuilder getBodyOrBuilder() {
        if (bodyBuilder_ != null) {
          return bodyBuilder_.getMessageOrBuilder();
        } else {
          return body_ == null ?
              poset.proto.PBlock.BlockBody.getDefaultInstance() : body_;
        }
      }
      /**
       * <code>optional .poset.proto.BlockBody Body = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          poset.proto.PBlock.BlockBody, poset.proto.PBlock.BlockBody.Builder, poset.proto.PBlock.BlockBodyOrBuilder> 
          getBodyFieldBuilder() {
        if (bodyBuilder_ == null) {
          bodyBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              poset.proto.PBlock.BlockBody, poset.proto.PBlock.BlockBody.Builder, poset.proto.PBlock.BlockBodyOrBuilder>(
                  getBody(),
                  getParentForChildren(),
                  isClean());
          body_ = null;
        }
        return bodyBuilder_;
      }

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.String> signatures_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetSignatures() {
        if (signatures_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              SignaturesDefaultEntryHolder.defaultEntry);
        }
        return signatures_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetMutableSignatures() {
        onChanged();;
        if (signatures_ == null) {
          signatures_ = com.google.protobuf.MapField.newMapField(
              SignaturesDefaultEntryHolder.defaultEntry);
        }
        if (!signatures_.isMutable()) {
          signatures_ = signatures_.copy();
        }
        return signatures_;
      }

      public int getSignaturesCount() {
        return internalGetSignatures().getMap().size();
      }
      /**
       * <code>map&lt;string, string&gt; Signatures = 2;</code>
       */

      public boolean containsSignatures(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetSignatures().getMap().containsKey(key);
      }
      /**
       * Use {@link #getSignaturesMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String> getSignatures() {
        return getSignaturesMap();
      }
      /**
       * <code>map&lt;string, string&gt; Signatures = 2;</code>
       */

      public java.util.Map<java.lang.String, java.lang.String> getSignaturesMap() {
        return internalGetSignatures().getMap();
      }
      /**
       * <code>map&lt;string, string&gt; Signatures = 2;</code>
       */

      public java.lang.String getSignaturesOrDefault(
          java.lang.String key,
          java.lang.String defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetSignatures().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, string&gt; Signatures = 2;</code>
       */

      public java.lang.String getSignaturesOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetSignatures().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearSignatures() {
        getMutableSignatures().clear();
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; Signatures = 2;</code>
       */

      public Builder removeSignatures(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        getMutableSignatures().remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String>
      getMutableSignatures() {
        return internalGetMutableSignatures().getMutableMap();
      }
      /**
       * <code>map&lt;string, string&gt; Signatures = 2;</code>
       */
      public Builder putSignatures(
          java.lang.String key,
          java.lang.String value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        getMutableSignatures().put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; Signatures = 2;</code>
       */

      public Builder putAllSignatures(
          java.util.Map<java.lang.String, java.lang.String> values) {
        getMutableSignatures().putAll(values);
        return this;
      }

      private com.google.protobuf.ByteString hash_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes hash = 3;</code>
       */
      public com.google.protobuf.ByteString getHash() {
        return hash_;
      }
      /**
       * <code>optional bytes hash = 3;</code>
       */
      public Builder setHash(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        hash_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes hash = 3;</code>
       */
      public Builder clearHash() {
        
        hash_ = getDefaultInstance().getHash();
        onChanged();
        return this;
      }

      private java.lang.Object hex_ = "";
      /**
       * <code>optional string hex = 4;</code>
       */
      public java.lang.String getHex() {
        java.lang.Object ref = hex_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          hex_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string hex = 4;</code>
       */
      public com.google.protobuf.ByteString
          getHexBytes() {
        java.lang.Object ref = hex_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          hex_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string hex = 4;</code>
       */
      public Builder setHex(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        hex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string hex = 4;</code>
       */
      public Builder clearHex() {
        
        hex_ = getDefaultInstance().getHex();
        onChanged();
        return this;
      }
      /**
       * <code>optional string hex = 4;</code>
       */
      public Builder setHexBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        hex_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString stateHash_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes StateHash = 5;</code>
       */
      public com.google.protobuf.ByteString getStateHash() {
        return stateHash_;
      }
      /**
       * <code>optional bytes StateHash = 5;</code>
       */
      public Builder setStateHash(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        stateHash_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes StateHash = 5;</code>
       */
      public Builder clearStateHash() {
        
        stateHash_ = getDefaultInstance().getStateHash();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString frameHash_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes FrameHash = 6;</code>
       */
      public com.google.protobuf.ByteString getFrameHash() {
        return frameHash_;
      }
      /**
       * <code>optional bytes FrameHash = 6;</code>
       */
      public Builder setFrameHash(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        frameHash_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes FrameHash = 6;</code>
       */
      public Builder clearFrameHash() {
        
        frameHash_ = getDefaultInstance().getFrameHash();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:poset.proto.Block)
    }

    // @@protoc_insertion_point(class_scope:poset.proto.Block)
    private static final poset.proto.PBlock.Block DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new poset.proto.PBlock.Block();
    }

    public static poset.proto.PBlock.Block getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Block>
        PARSER = new com.google.protobuf.AbstractParser<Block>() {
      public Block parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Block(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Block> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Block> getParserForType() {
      return PARSER;
    }

    public poset.proto.PBlock.Block getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_poset_proto_BlockBody_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_poset_proto_BlockBody_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_poset_proto_WireBlockSignature_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_poset_proto_WireBlockSignature_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_poset_proto_Block_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_poset_proto_Block_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_poset_proto_Block_SignaturesEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_poset_proto_Block_SignaturesEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027poset/proto/block.proto\022\013poset.proto\"G" +
      "\n\tBlockBody\022\r\n\005Index\030\001 \001(\003\022\025\n\rRoundRecei" +
      "ved\030\002 \001(\003\022\024\n\014Transactions\030\005 \003(\014\"6\n\022WireB" +
      "lockSignature\022\r\n\005Index\030\001 \001(\003\022\021\n\tSignatur" +
      "e\030\002 \001(\t\"\331\001\n\005Block\022$\n\004Body\030\001 \001(\0132\026.poset." +
      "proto.BlockBody\0226\n\nSignatures\030\002 \003(\0132\".po" +
      "set.proto.Block.SignaturesEntry\022\014\n\004hash\030" +
      "\003 \001(\014\022\013\n\003hex\030\004 \001(\t\022\021\n\tStateHash\030\005 \001(\014\022\021\n" +
      "\tFrameHash\030\006 \001(\014\0321\n\017SignaturesEntry\022\013\n\003k" +
      "ey\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001B\010B\006PBlockb\006p",
      "roto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_poset_proto_BlockBody_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_poset_proto_BlockBody_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_poset_proto_BlockBody_descriptor,
        new java.lang.String[] { "Index", "RoundReceived", "Transactions", });
    internal_static_poset_proto_WireBlockSignature_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_poset_proto_WireBlockSignature_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_poset_proto_WireBlockSignature_descriptor,
        new java.lang.String[] { "Index", "Signature", });
    internal_static_poset_proto_Block_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_poset_proto_Block_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_poset_proto_Block_descriptor,
        new java.lang.String[] { "Body", "Signatures", "Hash", "Hex", "StateHash", "FrameHash", });
    internal_static_poset_proto_Block_SignaturesEntry_descriptor =
      internal_static_poset_proto_Block_descriptor.getNestedTypes().get(0);
    internal_static_poset_proto_Block_SignaturesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_poset_proto_Block_SignaturesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
