// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: poset/proto/root.proto

package poset.proto;

public final class PRoot {
  private PRoot() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RootEventOrBuilder extends
      // @@protoc_insertion_point(interface_extends:poset.proto.RootEvent)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string Hash = 1;</code>
     */
    java.lang.String getHash();
    /**
     * <code>optional string Hash = 1;</code>
     */
    com.google.protobuf.ByteString
        getHashBytes();

    /**
     * <code>optional int64 CreatorID = 2;</code>
     */
    long getCreatorID();

    /**
     * <code>optional int64 Index = 3;</code>
     */
    long getIndex();

    /**
     * <code>optional int64 LamportTimestamp = 4;</code>
     */
    long getLamportTimestamp();

    /**
     * <code>optional int64 Round = 5;</code>
     */
    long getRound();
  }
  /**
   * Protobuf type {@code poset.proto.RootEvent}
   */
  public  static final class RootEvent extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:poset.proto.RootEvent)
      RootEventOrBuilder {
    // Use RootEvent.newBuilder() to construct.
    private RootEvent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RootEvent() {
      hash_ = "";
      creatorID_ = 0L;
      index_ = 0L;
      lamportTimestamp_ = 0L;
      round_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private RootEvent(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              hash_ = s;
              break;
            }
            case 16: {

              creatorID_ = input.readInt64();
              break;
            }
            case 24: {

              index_ = input.readInt64();
              break;
            }
            case 32: {

              lamportTimestamp_ = input.readInt64();
              break;
            }
            case 40: {

              round_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return poset.proto.PRoot.internal_static_poset_proto_RootEvent_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return poset.proto.PRoot.internal_static_poset_proto_RootEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              poset.proto.PRoot.RootEvent.class, poset.proto.PRoot.RootEvent.Builder.class);
    }

    public static final int HASH_FIELD_NUMBER = 1;
    private volatile java.lang.Object hash_;
    /**
     * <code>optional string Hash = 1;</code>
     */
    public java.lang.String getHash() {
      java.lang.Object ref = hash_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        hash_ = s;
        return s;
      }
    }
    /**
     * <code>optional string Hash = 1;</code>
     */
    public com.google.protobuf.ByteString
        getHashBytes() {
      java.lang.Object ref = hash_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        hash_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CREATORID_FIELD_NUMBER = 2;
    private long creatorID_;
    /**
     * <code>optional int64 CreatorID = 2;</code>
     */
    public long getCreatorID() {
      return creatorID_;
    }

    public static final int INDEX_FIELD_NUMBER = 3;
    private long index_;
    /**
     * <code>optional int64 Index = 3;</code>
     */
    public long getIndex() {
      return index_;
    }

    public static final int LAMPORTTIMESTAMP_FIELD_NUMBER = 4;
    private long lamportTimestamp_;
    /**
     * <code>optional int64 LamportTimestamp = 4;</code>
     */
    public long getLamportTimestamp() {
      return lamportTimestamp_;
    }

    public static final int ROUND_FIELD_NUMBER = 5;
    private long round_;
    /**
     * <code>optional int64 Round = 5;</code>
     */
    public long getRound() {
      return round_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getHashBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, hash_);
      }
      if (creatorID_ != 0L) {
        output.writeInt64(2, creatorID_);
      }
      if (index_ != 0L) {
        output.writeInt64(3, index_);
      }
      if (lamportTimestamp_ != 0L) {
        output.writeInt64(4, lamportTimestamp_);
      }
      if (round_ != 0L) {
        output.writeInt64(5, round_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getHashBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, hash_);
      }
      if (creatorID_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, creatorID_);
      }
      if (index_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, index_);
      }
      if (lamportTimestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, lamportTimestamp_);
      }
      if (round_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, round_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof poset.proto.PRoot.RootEvent)) {
        return super.equals(obj);
      }
      poset.proto.PRoot.RootEvent other = (poset.proto.PRoot.RootEvent) obj;

      boolean result = true;
      result = result && getHash()
          .equals(other.getHash());
      result = result && (getCreatorID()
          == other.getCreatorID());
      result = result && (getIndex()
          == other.getIndex());
      result = result && (getLamportTimestamp()
          == other.getLamportTimestamp());
      result = result && (getRound()
          == other.getRound());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + HASH_FIELD_NUMBER;
      hash = (53 * hash) + getHash().hashCode();
      hash = (37 * hash) + CREATORID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCreatorID());
      hash = (37 * hash) + INDEX_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getIndex());
      hash = (37 * hash) + LAMPORTTIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getLamportTimestamp());
      hash = (37 * hash) + ROUND_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getRound());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static poset.proto.PRoot.RootEvent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static poset.proto.PRoot.RootEvent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static poset.proto.PRoot.RootEvent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static poset.proto.PRoot.RootEvent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static poset.proto.PRoot.RootEvent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static poset.proto.PRoot.RootEvent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static poset.proto.PRoot.RootEvent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static poset.proto.PRoot.RootEvent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static poset.proto.PRoot.RootEvent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static poset.proto.PRoot.RootEvent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(poset.proto.PRoot.RootEvent prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code poset.proto.RootEvent}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:poset.proto.RootEvent)
        poset.proto.PRoot.RootEventOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return poset.proto.PRoot.internal_static_poset_proto_RootEvent_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return poset.proto.PRoot.internal_static_poset_proto_RootEvent_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                poset.proto.PRoot.RootEvent.class, poset.proto.PRoot.RootEvent.Builder.class);
      }

      // Construct using poset.proto.PRoot.RootEvent.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        hash_ = "";

        creatorID_ = 0L;

        index_ = 0L;

        lamportTimestamp_ = 0L;

        round_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return poset.proto.PRoot.internal_static_poset_proto_RootEvent_descriptor;
      }

      public poset.proto.PRoot.RootEvent getDefaultInstanceForType() {
        return poset.proto.PRoot.RootEvent.getDefaultInstance();
      }

      public poset.proto.PRoot.RootEvent build() {
        poset.proto.PRoot.RootEvent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public poset.proto.PRoot.RootEvent buildPartial() {
        poset.proto.PRoot.RootEvent result = new poset.proto.PRoot.RootEvent(this);
        result.hash_ = hash_;
        result.creatorID_ = creatorID_;
        result.index_ = index_;
        result.lamportTimestamp_ = lamportTimestamp_;
        result.round_ = round_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof poset.proto.PRoot.RootEvent) {
          return mergeFrom((poset.proto.PRoot.RootEvent)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(poset.proto.PRoot.RootEvent other) {
        if (other == poset.proto.PRoot.RootEvent.getDefaultInstance()) return this;
        if (!other.getHash().isEmpty()) {
          hash_ = other.hash_;
          onChanged();
        }
        if (other.getCreatorID() != 0L) {
          setCreatorID(other.getCreatorID());
        }
        if (other.getIndex() != 0L) {
          setIndex(other.getIndex());
        }
        if (other.getLamportTimestamp() != 0L) {
          setLamportTimestamp(other.getLamportTimestamp());
        }
        if (other.getRound() != 0L) {
          setRound(other.getRound());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        poset.proto.PRoot.RootEvent parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (poset.proto.PRoot.RootEvent) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object hash_ = "";
      /**
       * <code>optional string Hash = 1;</code>
       */
      public java.lang.String getHash() {
        java.lang.Object ref = hash_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          hash_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string Hash = 1;</code>
       */
      public com.google.protobuf.ByteString
          getHashBytes() {
        java.lang.Object ref = hash_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          hash_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string Hash = 1;</code>
       */
      public Builder setHash(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        hash_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string Hash = 1;</code>
       */
      public Builder clearHash() {
        
        hash_ = getDefaultInstance().getHash();
        onChanged();
        return this;
      }
      /**
       * <code>optional string Hash = 1;</code>
       */
      public Builder setHashBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        hash_ = value;
        onChanged();
        return this;
      }

      private long creatorID_ ;
      /**
       * <code>optional int64 CreatorID = 2;</code>
       */
      public long getCreatorID() {
        return creatorID_;
      }
      /**
       * <code>optional int64 CreatorID = 2;</code>
       */
      public Builder setCreatorID(long value) {
        
        creatorID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 CreatorID = 2;</code>
       */
      public Builder clearCreatorID() {
        
        creatorID_ = 0L;
        onChanged();
        return this;
      }

      private long index_ ;
      /**
       * <code>optional int64 Index = 3;</code>
       */
      public long getIndex() {
        return index_;
      }
      /**
       * <code>optional int64 Index = 3;</code>
       */
      public Builder setIndex(long value) {
        
        index_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 Index = 3;</code>
       */
      public Builder clearIndex() {
        
        index_ = 0L;
        onChanged();
        return this;
      }

      private long lamportTimestamp_ ;
      /**
       * <code>optional int64 LamportTimestamp = 4;</code>
       */
      public long getLamportTimestamp() {
        return lamportTimestamp_;
      }
      /**
       * <code>optional int64 LamportTimestamp = 4;</code>
       */
      public Builder setLamportTimestamp(long value) {
        
        lamportTimestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 LamportTimestamp = 4;</code>
       */
      public Builder clearLamportTimestamp() {
        
        lamportTimestamp_ = 0L;
        onChanged();
        return this;
      }

      private long round_ ;
      /**
       * <code>optional int64 Round = 5;</code>
       */
      public long getRound() {
        return round_;
      }
      /**
       * <code>optional int64 Round = 5;</code>
       */
      public Builder setRound(long value) {
        
        round_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 Round = 5;</code>
       */
      public Builder clearRound() {
        
        round_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:poset.proto.RootEvent)
    }

    // @@protoc_insertion_point(class_scope:poset.proto.RootEvent)
    private static final poset.proto.PRoot.RootEvent DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new poset.proto.PRoot.RootEvent();
    }

    public static poset.proto.PRoot.RootEvent getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RootEvent>
        PARSER = new com.google.protobuf.AbstractParser<RootEvent>() {
      public RootEvent parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new RootEvent(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RootEvent> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RootEvent> getParserForType() {
      return PARSER;
    }

    public poset.proto.PRoot.RootEvent getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface RootOrBuilder extends
      // @@protoc_insertion_point(interface_extends:poset.proto.Root)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int64 NextRound = 1;</code>
     */
    long getNextRound();

    /**
     * <code>optional .poset.proto.RootEvent SelfParent = 2;</code>
     */
    boolean hasSelfParent();
    /**
     * <code>optional .poset.proto.RootEvent SelfParent = 2;</code>
     */
    poset.proto.PRoot.RootEvent getSelfParent();
    /**
     * <code>optional .poset.proto.RootEvent SelfParent = 2;</code>
     */
    poset.proto.PRoot.RootEventOrBuilder getSelfParentOrBuilder();

    /**
     * <code>map&lt;string, .poset.proto.RootEvent&gt; Others = 3;</code>
     */
    int getOthersCount();
    /**
     * <code>map&lt;string, .poset.proto.RootEvent&gt; Others = 3;</code>
     */
    boolean containsOthers(
        java.lang.String key);
    /**
     * Use {@link #getOthersMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, poset.proto.PRoot.RootEvent>
    getOthers();
    /**
     * <code>map&lt;string, .poset.proto.RootEvent&gt; Others = 3;</code>
     */
    java.util.Map<java.lang.String, poset.proto.PRoot.RootEvent>
    getOthersMap();
    /**
     * <code>map&lt;string, .poset.proto.RootEvent&gt; Others = 3;</code>
     */

    poset.proto.PRoot.RootEvent getOthersOrDefault(
        java.lang.String key,
        poset.proto.PRoot.RootEvent defaultValue);
    /**
     * <code>map&lt;string, .poset.proto.RootEvent&gt; Others = 3;</code>
     */

    poset.proto.PRoot.RootEvent getOthersOrThrow(
        java.lang.String key);
  }
  /**
   * Protobuf type {@code poset.proto.Root}
   */
  public  static final class Root extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:poset.proto.Root)
      RootOrBuilder {
    // Use Root.newBuilder() to construct.
    private Root(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Root() {
      nextRound_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Root(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              nextRound_ = input.readInt64();
              break;
            }
            case 18: {
              poset.proto.PRoot.RootEvent.Builder subBuilder = null;
              if (selfParent_ != null) {
                subBuilder = selfParent_.toBuilder();
              }
              selfParent_ = input.readMessage(poset.proto.PRoot.RootEvent.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(selfParent_);
                selfParent_ = subBuilder.buildPartial();
              }

              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                others_ = com.google.protobuf.MapField.newMapField(
                    OthersDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000004;
              }
              com.google.protobuf.MapEntry<java.lang.String, poset.proto.PRoot.RootEvent>
              others = input.readMessage(
                  OthersDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              others_.getMutableMap().put(others.getKey(), others.getValue());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return poset.proto.PRoot.internal_static_poset_proto_Root_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 3:
          return internalGetOthers();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return poset.proto.PRoot.internal_static_poset_proto_Root_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              poset.proto.PRoot.Root.class, poset.proto.PRoot.Root.Builder.class);
    }

    private int bitField0_;
    public static final int NEXTROUND_FIELD_NUMBER = 1;
    private long nextRound_;
    /**
     * <code>optional int64 NextRound = 1;</code>
     */
    public long getNextRound() {
      return nextRound_;
    }

    public static final int SELFPARENT_FIELD_NUMBER = 2;
    private poset.proto.PRoot.RootEvent selfParent_;
    /**
     * <code>optional .poset.proto.RootEvent SelfParent = 2;</code>
     */
    public boolean hasSelfParent() {
      return selfParent_ != null;
    }
    /**
     * <code>optional .poset.proto.RootEvent SelfParent = 2;</code>
     */
    public poset.proto.PRoot.RootEvent getSelfParent() {
      return selfParent_ == null ? poset.proto.PRoot.RootEvent.getDefaultInstance() : selfParent_;
    }
    /**
     * <code>optional .poset.proto.RootEvent SelfParent = 2;</code>
     */
    public poset.proto.PRoot.RootEventOrBuilder getSelfParentOrBuilder() {
      return getSelfParent();
    }

    public static final int OTHERS_FIELD_NUMBER = 3;
    private static final class OthersDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, poset.proto.PRoot.RootEvent> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, poset.proto.PRoot.RootEvent>newDefaultInstance(
                  poset.proto.PRoot.internal_static_poset_proto_Root_OthersEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.MESSAGE,
                  poset.proto.PRoot.RootEvent.getDefaultInstance());
    }
    private com.google.protobuf.MapField<
        java.lang.String, poset.proto.PRoot.RootEvent> others_;
    private com.google.protobuf.MapField<java.lang.String, poset.proto.PRoot.RootEvent>
    internalGetOthers() {
      if (others_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            OthersDefaultEntryHolder.defaultEntry);
      }
      return others_;
    }

    public int getOthersCount() {
      return internalGetOthers().getMap().size();
    }
    /**
     * <code>map&lt;string, .poset.proto.RootEvent&gt; Others = 3;</code>
     */

    public boolean containsOthers(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetOthers().getMap().containsKey(key);
    }
    /**
     * Use {@link #getOthersMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, poset.proto.PRoot.RootEvent> getOthers() {
      return getOthersMap();
    }
    /**
     * <code>map&lt;string, .poset.proto.RootEvent&gt; Others = 3;</code>
     */

    public java.util.Map<java.lang.String, poset.proto.PRoot.RootEvent> getOthersMap() {
      return internalGetOthers().getMap();
    }
    /**
     * <code>map&lt;string, .poset.proto.RootEvent&gt; Others = 3;</code>
     */

    public poset.proto.PRoot.RootEvent getOthersOrDefault(
        java.lang.String key,
        poset.proto.PRoot.RootEvent defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, poset.proto.PRoot.RootEvent> map =
          internalGetOthers().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, .poset.proto.RootEvent&gt; Others = 3;</code>
     */

    public poset.proto.PRoot.RootEvent getOthersOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, poset.proto.PRoot.RootEvent> map =
          internalGetOthers().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (nextRound_ != 0L) {
        output.writeInt64(1, nextRound_);
      }
      if (selfParent_ != null) {
        output.writeMessage(2, getSelfParent());
      }
      for (java.util.Map.Entry<java.lang.String, poset.proto.PRoot.RootEvent> entry
           : internalGetOthers().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, poset.proto.PRoot.RootEvent>
        others = OthersDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        output.writeMessage(3, others);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (nextRound_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, nextRound_);
      }
      if (selfParent_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getSelfParent());
      }
      for (java.util.Map.Entry<java.lang.String, poset.proto.PRoot.RootEvent> entry
           : internalGetOthers().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, poset.proto.PRoot.RootEvent>
        others = OthersDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(3, others);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof poset.proto.PRoot.Root)) {
        return super.equals(obj);
      }
      poset.proto.PRoot.Root other = (poset.proto.PRoot.Root) obj;

      boolean result = true;
      result = result && (getNextRound()
          == other.getNextRound());
      result = result && (hasSelfParent() == other.hasSelfParent());
      if (hasSelfParent()) {
        result = result && getSelfParent()
            .equals(other.getSelfParent());
      }
      result = result && internalGetOthers().equals(
          other.internalGetOthers());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + NEXTROUND_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getNextRound());
      if (hasSelfParent()) {
        hash = (37 * hash) + SELFPARENT_FIELD_NUMBER;
        hash = (53 * hash) + getSelfParent().hashCode();
      }
      if (!internalGetOthers().getMap().isEmpty()) {
        hash = (37 * hash) + OTHERS_FIELD_NUMBER;
        hash = (53 * hash) + internalGetOthers().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static poset.proto.PRoot.Root parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static poset.proto.PRoot.Root parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static poset.proto.PRoot.Root parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static poset.proto.PRoot.Root parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static poset.proto.PRoot.Root parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static poset.proto.PRoot.Root parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static poset.proto.PRoot.Root parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static poset.proto.PRoot.Root parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static poset.proto.PRoot.Root parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static poset.proto.PRoot.Root parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(poset.proto.PRoot.Root prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code poset.proto.Root}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:poset.proto.Root)
        poset.proto.PRoot.RootOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return poset.proto.PRoot.internal_static_poset_proto_Root_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 3:
            return internalGetOthers();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 3:
            return internalGetMutableOthers();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return poset.proto.PRoot.internal_static_poset_proto_Root_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                poset.proto.PRoot.Root.class, poset.proto.PRoot.Root.Builder.class);
      }

      // Construct using poset.proto.PRoot.Root.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        nextRound_ = 0L;

        if (selfParentBuilder_ == null) {
          selfParent_ = null;
        } else {
          selfParent_ = null;
          selfParentBuilder_ = null;
        }
        internalGetMutableOthers().clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return poset.proto.PRoot.internal_static_poset_proto_Root_descriptor;
      }

      public poset.proto.PRoot.Root getDefaultInstanceForType() {
        return poset.proto.PRoot.Root.getDefaultInstance();
      }

      public poset.proto.PRoot.Root build() {
        poset.proto.PRoot.Root result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public poset.proto.PRoot.Root buildPartial() {
        poset.proto.PRoot.Root result = new poset.proto.PRoot.Root(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.nextRound_ = nextRound_;
        if (selfParentBuilder_ == null) {
          result.selfParent_ = selfParent_;
        } else {
          result.selfParent_ = selfParentBuilder_.build();
        }
        result.others_ = internalGetOthers();
        result.others_.makeImmutable();
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof poset.proto.PRoot.Root) {
          return mergeFrom((poset.proto.PRoot.Root)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(poset.proto.PRoot.Root other) {
        if (other == poset.proto.PRoot.Root.getDefaultInstance()) return this;
        if (other.getNextRound() != 0L) {
          setNextRound(other.getNextRound());
        }
        if (other.hasSelfParent()) {
          mergeSelfParent(other.getSelfParent());
        }
        internalGetMutableOthers().mergeFrom(
            other.internalGetOthers());
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        poset.proto.PRoot.Root parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (poset.proto.PRoot.Root) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long nextRound_ ;
      /**
       * <code>optional int64 NextRound = 1;</code>
       */
      public long getNextRound() {
        return nextRound_;
      }
      /**
       * <code>optional int64 NextRound = 1;</code>
       */
      public Builder setNextRound(long value) {
        
        nextRound_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 NextRound = 1;</code>
       */
      public Builder clearNextRound() {
        
        nextRound_ = 0L;
        onChanged();
        return this;
      }

      private poset.proto.PRoot.RootEvent selfParent_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          poset.proto.PRoot.RootEvent, poset.proto.PRoot.RootEvent.Builder, poset.proto.PRoot.RootEventOrBuilder> selfParentBuilder_;
      /**
       * <code>optional .poset.proto.RootEvent SelfParent = 2;</code>
       */
      public boolean hasSelfParent() {
        return selfParentBuilder_ != null || selfParent_ != null;
      }
      /**
       * <code>optional .poset.proto.RootEvent SelfParent = 2;</code>
       */
      public poset.proto.PRoot.RootEvent getSelfParent() {
        if (selfParentBuilder_ == null) {
          return selfParent_ == null ? poset.proto.PRoot.RootEvent.getDefaultInstance() : selfParent_;
        } else {
          return selfParentBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .poset.proto.RootEvent SelfParent = 2;</code>
       */
      public Builder setSelfParent(poset.proto.PRoot.RootEvent value) {
        if (selfParentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          selfParent_ = value;
          onChanged();
        } else {
          selfParentBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .poset.proto.RootEvent SelfParent = 2;</code>
       */
      public Builder setSelfParent(
          poset.proto.PRoot.RootEvent.Builder builderForValue) {
        if (selfParentBuilder_ == null) {
          selfParent_ = builderForValue.build();
          onChanged();
        } else {
          selfParentBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .poset.proto.RootEvent SelfParent = 2;</code>
       */
      public Builder mergeSelfParent(poset.proto.PRoot.RootEvent value) {
        if (selfParentBuilder_ == null) {
          if (selfParent_ != null) {
            selfParent_ =
              poset.proto.PRoot.RootEvent.newBuilder(selfParent_).mergeFrom(value).buildPartial();
          } else {
            selfParent_ = value;
          }
          onChanged();
        } else {
          selfParentBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .poset.proto.RootEvent SelfParent = 2;</code>
       */
      public Builder clearSelfParent() {
        if (selfParentBuilder_ == null) {
          selfParent_ = null;
          onChanged();
        } else {
          selfParent_ = null;
          selfParentBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .poset.proto.RootEvent SelfParent = 2;</code>
       */
      public poset.proto.PRoot.RootEvent.Builder getSelfParentBuilder() {
        
        onChanged();
        return getSelfParentFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .poset.proto.RootEvent SelfParent = 2;</code>
       */
      public poset.proto.PRoot.RootEventOrBuilder getSelfParentOrBuilder() {
        if (selfParentBuilder_ != null) {
          return selfParentBuilder_.getMessageOrBuilder();
        } else {
          return selfParent_ == null ?
              poset.proto.PRoot.RootEvent.getDefaultInstance() : selfParent_;
        }
      }
      /**
       * <code>optional .poset.proto.RootEvent SelfParent = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          poset.proto.PRoot.RootEvent, poset.proto.PRoot.RootEvent.Builder, poset.proto.PRoot.RootEventOrBuilder> 
          getSelfParentFieldBuilder() {
        if (selfParentBuilder_ == null) {
          selfParentBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              poset.proto.PRoot.RootEvent, poset.proto.PRoot.RootEvent.Builder, poset.proto.PRoot.RootEventOrBuilder>(
                  getSelfParent(),
                  getParentForChildren(),
                  isClean());
          selfParent_ = null;
        }
        return selfParentBuilder_;
      }

      private com.google.protobuf.MapField<
          java.lang.String, poset.proto.PRoot.RootEvent> others_;
      private com.google.protobuf.MapField<java.lang.String, poset.proto.PRoot.RootEvent>
      internalGetOthers() {
        if (others_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              OthersDefaultEntryHolder.defaultEntry);
        }
        return others_;
      }
      private com.google.protobuf.MapField<java.lang.String, poset.proto.PRoot.RootEvent>
      internalGetMutableOthers() {
        onChanged();;
        if (others_ == null) {
          others_ = com.google.protobuf.MapField.newMapField(
              OthersDefaultEntryHolder.defaultEntry);
        }
        if (!others_.isMutable()) {
          others_ = others_.copy();
        }
        return others_;
      }

      public int getOthersCount() {
        return internalGetOthers().getMap().size();
      }
      /**
       * <code>map&lt;string, .poset.proto.RootEvent&gt; Others = 3;</code>
       */

      public boolean containsOthers(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetOthers().getMap().containsKey(key);
      }
      /**
       * Use {@link #getOthersMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, poset.proto.PRoot.RootEvent> getOthers() {
        return getOthersMap();
      }
      /**
       * <code>map&lt;string, .poset.proto.RootEvent&gt; Others = 3;</code>
       */

      public java.util.Map<java.lang.String, poset.proto.PRoot.RootEvent> getOthersMap() {
        return internalGetOthers().getMap();
      }
      /**
       * <code>map&lt;string, .poset.proto.RootEvent&gt; Others = 3;</code>
       */

      public poset.proto.PRoot.RootEvent getOthersOrDefault(
          java.lang.String key,
          poset.proto.PRoot.RootEvent defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, poset.proto.PRoot.RootEvent> map =
            internalGetOthers().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, .poset.proto.RootEvent&gt; Others = 3;</code>
       */

      public poset.proto.PRoot.RootEvent getOthersOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, poset.proto.PRoot.RootEvent> map =
            internalGetOthers().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearOthers() {
        getMutableOthers().clear();
        return this;
      }
      /**
       * <code>map&lt;string, .poset.proto.RootEvent&gt; Others = 3;</code>
       */

      public Builder removeOthers(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        getMutableOthers().remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, poset.proto.PRoot.RootEvent>
      getMutableOthers() {
        return internalGetMutableOthers().getMutableMap();
      }
      /**
       * <code>map&lt;string, .poset.proto.RootEvent&gt; Others = 3;</code>
       */
      public Builder putOthers(
          java.lang.String key,
          poset.proto.PRoot.RootEvent value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        getMutableOthers().put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, .poset.proto.RootEvent&gt; Others = 3;</code>
       */

      public Builder putAllOthers(
          java.util.Map<java.lang.String, poset.proto.PRoot.RootEvent> values) {
        getMutableOthers().putAll(values);
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:poset.proto.Root)
    }

    // @@protoc_insertion_point(class_scope:poset.proto.Root)
    private static final poset.proto.PRoot.Root DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new poset.proto.PRoot.Root();
    }

    public static poset.proto.PRoot.Root getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Root>
        PARSER = new com.google.protobuf.AbstractParser<Root>() {
      public Root parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Root(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Root> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Root> getParserForType() {
      return PARSER;
    }

    public poset.proto.PRoot.Root getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_poset_proto_RootEvent_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_poset_proto_RootEvent_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_poset_proto_Root_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_poset_proto_Root_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_poset_proto_Root_OthersEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_poset_proto_Root_OthersEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026poset/proto/root.proto\022\013poset.proto\"d\n" +
      "\tRootEvent\022\014\n\004Hash\030\001 \001(\t\022\021\n\tCreatorID\030\002 " +
      "\001(\003\022\r\n\005Index\030\003 \001(\003\022\030\n\020LamportTimestamp\030\004" +
      " \001(\003\022\r\n\005Round\030\005 \001(\003\"\273\001\n\004Root\022\021\n\tNextRoun" +
      "d\030\001 \001(\003\022*\n\nSelfParent\030\002 \001(\0132\026.poset.prot" +
      "o.RootEvent\022-\n\006Others\030\003 \003(\0132\035.poset.prot" +
      "o.Root.OthersEntry\032E\n\013OthersEntry\022\013\n\003key" +
      "\030\001 \001(\t\022%\n\005value\030\002 \001(\0132\026.poset.proto.Root" +
      "Event:\0028\001B\007B\005PRootb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_poset_proto_RootEvent_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_poset_proto_RootEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_poset_proto_RootEvent_descriptor,
        new java.lang.String[] { "Hash", "CreatorID", "Index", "LamportTimestamp", "Round", });
    internal_static_poset_proto_Root_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_poset_proto_Root_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_poset_proto_Root_descriptor,
        new java.lang.String[] { "NextRound", "SelfParent", "Others", });
    internal_static_poset_proto_Root_OthersEntry_descriptor =
      internal_static_poset_proto_Root_descriptor.getNestedTypes().get(0);
    internal_static_poset_proto_Root_OthersEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_poset_proto_Root_OthersEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
