// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: poset/proto/roundInfo.proto

package poset.proto;

public final class PRoundInfo {
  private PRoundInfo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code poset.proto.Trilean}
   */
  public enum Trilean
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>UNDEFINED = 0;</code>
     */
    UNDEFINED(0),
    /**
     * <code>TRUE = 1;</code>
     */
    TRUE(1),
    /**
     * <code>FALSE = 2;</code>
     */
    FALSE(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>UNDEFINED = 0;</code>
     */
    public static final int UNDEFINED_VALUE = 0;
    /**
     * <code>TRUE = 1;</code>
     */
    public static final int TRUE_VALUE = 1;
    /**
     * <code>FALSE = 2;</code>
     */
    public static final int FALSE_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Trilean valueOf(int value) {
      return forNumber(value);
    }

    public static Trilean forNumber(int value) {
      switch (value) {
        case 0: return UNDEFINED;
        case 1: return TRUE;
        case 2: return FALSE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Trilean>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Trilean> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Trilean>() {
            public Trilean findValueByNumber(int number) {
              return Trilean.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return poset.proto.PRoundInfo.getDescriptor().getEnumTypes().get(0);
    }

    private static final Trilean[] VALUES = values();

    public static Trilean valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Trilean(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:poset.proto.Trilean)
  }

  public interface RoundEventOrBuilder extends
      // @@protoc_insertion_point(interface_extends:poset.proto.RoundEvent)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bool Consensus = 1;</code>
     */
    boolean getConsensus();

    /**
     * <code>optional bool Witness = 2;</code>
     */
    boolean getWitness();

    /**
     * <code>optional .poset.proto.Trilean Famous = 3;</code>
     */
    int getFamousValue();
    /**
     * <code>optional .poset.proto.Trilean Famous = 3;</code>
     */
    poset.proto.PRoundInfo.Trilean getFamous();
  }
  /**
   * Protobuf type {@code poset.proto.RoundEvent}
   */
  public  static final class RoundEvent extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:poset.proto.RoundEvent)
      RoundEventOrBuilder {
    // Use RoundEvent.newBuilder() to construct.
    private RoundEvent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RoundEvent() {
      consensus_ = false;
      witness_ = false;
      famous_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private RoundEvent(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              consensus_ = input.readBool();
              break;
            }
            case 16: {

              witness_ = input.readBool();
              break;
            }
            case 24: {
              int rawValue = input.readEnum();

              famous_ = rawValue;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return poset.proto.PRoundInfo.internal_static_poset_proto_RoundEvent_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return poset.proto.PRoundInfo.internal_static_poset_proto_RoundEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              poset.proto.PRoundInfo.RoundEvent.class, poset.proto.PRoundInfo.RoundEvent.Builder.class);
    }

    public static final int CONSENSUS_FIELD_NUMBER = 1;
    private boolean consensus_;
    /**
     * <code>optional bool Consensus = 1;</code>
     */
    public boolean getConsensus() {
      return consensus_;
    }

    public static final int WITNESS_FIELD_NUMBER = 2;
    private boolean witness_;
    /**
     * <code>optional bool Witness = 2;</code>
     */
    public boolean getWitness() {
      return witness_;
    }

    public static final int FAMOUS_FIELD_NUMBER = 3;
    private int famous_;
    /**
     * <code>optional .poset.proto.Trilean Famous = 3;</code>
     */
    public int getFamousValue() {
      return famous_;
    }
    /**
     * <code>optional .poset.proto.Trilean Famous = 3;</code>
     */
    public poset.proto.PRoundInfo.Trilean getFamous() {
      poset.proto.PRoundInfo.Trilean result = poset.proto.PRoundInfo.Trilean.valueOf(famous_);
      return result == null ? poset.proto.PRoundInfo.Trilean.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (consensus_ != false) {
        output.writeBool(1, consensus_);
      }
      if (witness_ != false) {
        output.writeBool(2, witness_);
      }
      if (famous_ != poset.proto.PRoundInfo.Trilean.UNDEFINED.getNumber()) {
        output.writeEnum(3, famous_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (consensus_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, consensus_);
      }
      if (witness_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, witness_);
      }
      if (famous_ != poset.proto.PRoundInfo.Trilean.UNDEFINED.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, famous_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof poset.proto.PRoundInfo.RoundEvent)) {
        return super.equals(obj);
      }
      poset.proto.PRoundInfo.RoundEvent other = (poset.proto.PRoundInfo.RoundEvent) obj;

      boolean result = true;
      result = result && (getConsensus()
          == other.getConsensus());
      result = result && (getWitness()
          == other.getWitness());
      result = result && famous_ == other.famous_;
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + CONSENSUS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getConsensus());
      hash = (37 * hash) + WITNESS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getWitness());
      hash = (37 * hash) + FAMOUS_FIELD_NUMBER;
      hash = (53 * hash) + famous_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static poset.proto.PRoundInfo.RoundEvent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static poset.proto.PRoundInfo.RoundEvent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static poset.proto.PRoundInfo.RoundEvent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static poset.proto.PRoundInfo.RoundEvent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static poset.proto.PRoundInfo.RoundEvent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static poset.proto.PRoundInfo.RoundEvent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static poset.proto.PRoundInfo.RoundEvent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static poset.proto.PRoundInfo.RoundEvent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static poset.proto.PRoundInfo.RoundEvent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static poset.proto.PRoundInfo.RoundEvent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(poset.proto.PRoundInfo.RoundEvent prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code poset.proto.RoundEvent}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:poset.proto.RoundEvent)
        poset.proto.PRoundInfo.RoundEventOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return poset.proto.PRoundInfo.internal_static_poset_proto_RoundEvent_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return poset.proto.PRoundInfo.internal_static_poset_proto_RoundEvent_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                poset.proto.PRoundInfo.RoundEvent.class, poset.proto.PRoundInfo.RoundEvent.Builder.class);
      }

      // Construct using poset.proto.PRoundInfo.RoundEvent.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        consensus_ = false;

        witness_ = false;

        famous_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return poset.proto.PRoundInfo.internal_static_poset_proto_RoundEvent_descriptor;
      }

      public poset.proto.PRoundInfo.RoundEvent getDefaultInstanceForType() {
        return poset.proto.PRoundInfo.RoundEvent.getDefaultInstance();
      }

      public poset.proto.PRoundInfo.RoundEvent build() {
        poset.proto.PRoundInfo.RoundEvent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public poset.proto.PRoundInfo.RoundEvent buildPartial() {
        poset.proto.PRoundInfo.RoundEvent result = new poset.proto.PRoundInfo.RoundEvent(this);
        result.consensus_ = consensus_;
        result.witness_ = witness_;
        result.famous_ = famous_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof poset.proto.PRoundInfo.RoundEvent) {
          return mergeFrom((poset.proto.PRoundInfo.RoundEvent)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(poset.proto.PRoundInfo.RoundEvent other) {
        if (other == poset.proto.PRoundInfo.RoundEvent.getDefaultInstance()) return this;
        if (other.getConsensus() != false) {
          setConsensus(other.getConsensus());
        }
        if (other.getWitness() != false) {
          setWitness(other.getWitness());
        }
        if (other.famous_ != 0) {
          setFamousValue(other.getFamousValue());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        poset.proto.PRoundInfo.RoundEvent parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (poset.proto.PRoundInfo.RoundEvent) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private boolean consensus_ ;
      /**
       * <code>optional bool Consensus = 1;</code>
       */
      public boolean getConsensus() {
        return consensus_;
      }
      /**
       * <code>optional bool Consensus = 1;</code>
       */
      public Builder setConsensus(boolean value) {
        
        consensus_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool Consensus = 1;</code>
       */
      public Builder clearConsensus() {
        
        consensus_ = false;
        onChanged();
        return this;
      }

      private boolean witness_ ;
      /**
       * <code>optional bool Witness = 2;</code>
       */
      public boolean getWitness() {
        return witness_;
      }
      /**
       * <code>optional bool Witness = 2;</code>
       */
      public Builder setWitness(boolean value) {
        
        witness_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool Witness = 2;</code>
       */
      public Builder clearWitness() {
        
        witness_ = false;
        onChanged();
        return this;
      }

      private int famous_ = 0;
      /**
       * <code>optional .poset.proto.Trilean Famous = 3;</code>
       */
      public int getFamousValue() {
        return famous_;
      }
      /**
       * <code>optional .poset.proto.Trilean Famous = 3;</code>
       */
      public Builder setFamousValue(int value) {
        famous_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .poset.proto.Trilean Famous = 3;</code>
       */
      public poset.proto.PRoundInfo.Trilean getFamous() {
        poset.proto.PRoundInfo.Trilean result = poset.proto.PRoundInfo.Trilean.valueOf(famous_);
        return result == null ? poset.proto.PRoundInfo.Trilean.UNRECOGNIZED : result;
      }
      /**
       * <code>optional .poset.proto.Trilean Famous = 3;</code>
       */
      public Builder setFamous(poset.proto.PRoundInfo.Trilean value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        famous_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .poset.proto.Trilean Famous = 3;</code>
       */
      public Builder clearFamous() {
        
        famous_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:poset.proto.RoundEvent)
    }

    // @@protoc_insertion_point(class_scope:poset.proto.RoundEvent)
    private static final poset.proto.PRoundInfo.RoundEvent DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new poset.proto.PRoundInfo.RoundEvent();
    }

    public static poset.proto.PRoundInfo.RoundEvent getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RoundEvent>
        PARSER = new com.google.protobuf.AbstractParser<RoundEvent>() {
      public RoundEvent parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new RoundEvent(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RoundEvent> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RoundEvent> getParserForType() {
      return PARSER;
    }

    public poset.proto.PRoundInfo.RoundEvent getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface RoundInfoMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:poset.proto.RoundInfoMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>map&lt;string, .poset.proto.RoundEvent&gt; Events = 1;</code>
     */
    int getEventsCount();
    /**
     * <code>map&lt;string, .poset.proto.RoundEvent&gt; Events = 1;</code>
     */
    boolean containsEvents(
        java.lang.String key);
    /**
     * Use {@link #getEventsMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, poset.proto.PRoundInfo.RoundEvent>
    getEvents();
    /**
     * <code>map&lt;string, .poset.proto.RoundEvent&gt; Events = 1;</code>
     */
    java.util.Map<java.lang.String, poset.proto.PRoundInfo.RoundEvent>
    getEventsMap();
    /**
     * <code>map&lt;string, .poset.proto.RoundEvent&gt; Events = 1;</code>
     */

    poset.proto.PRoundInfo.RoundEvent getEventsOrDefault(
        java.lang.String key,
        poset.proto.PRoundInfo.RoundEvent defaultValue);
    /**
     * <code>map&lt;string, .poset.proto.RoundEvent&gt; Events = 1;</code>
     */

    poset.proto.PRoundInfo.RoundEvent getEventsOrThrow(
        java.lang.String key);
  }
  /**
   * Protobuf type {@code poset.proto.RoundInfoMessage}
   */
  public  static final class RoundInfoMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:poset.proto.RoundInfoMessage)
      RoundInfoMessageOrBuilder {
    // Use RoundInfoMessage.newBuilder() to construct.
    private RoundInfoMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RoundInfoMessage() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private RoundInfoMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                events_ = com.google.protobuf.MapField.newMapField(
                    EventsDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000001;
              }
              com.google.protobuf.MapEntry<java.lang.String, poset.proto.PRoundInfo.RoundEvent>
              events = input.readMessage(
                  EventsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              events_.getMutableMap().put(events.getKey(), events.getValue());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return poset.proto.PRoundInfo.internal_static_poset_proto_RoundInfoMessage_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetEvents();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return poset.proto.PRoundInfo.internal_static_poset_proto_RoundInfoMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              poset.proto.PRoundInfo.RoundInfoMessage.class, poset.proto.PRoundInfo.RoundInfoMessage.Builder.class);
    }

    public static final int EVENTS_FIELD_NUMBER = 1;
    private static final class EventsDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, poset.proto.PRoundInfo.RoundEvent> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, poset.proto.PRoundInfo.RoundEvent>newDefaultInstance(
                  poset.proto.PRoundInfo.internal_static_poset_proto_RoundInfoMessage_EventsEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.MESSAGE,
                  poset.proto.PRoundInfo.RoundEvent.getDefaultInstance());
    }
    private com.google.protobuf.MapField<
        java.lang.String, poset.proto.PRoundInfo.RoundEvent> events_;
    private com.google.protobuf.MapField<java.lang.String, poset.proto.PRoundInfo.RoundEvent>
    internalGetEvents() {
      if (events_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            EventsDefaultEntryHolder.defaultEntry);
      }
      return events_;
    }

    public int getEventsCount() {
      return internalGetEvents().getMap().size();
    }
    /**
     * <code>map&lt;string, .poset.proto.RoundEvent&gt; Events = 1;</code>
     */

    public boolean containsEvents(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetEvents().getMap().containsKey(key);
    }
    /**
     * Use {@link #getEventsMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, poset.proto.PRoundInfo.RoundEvent> getEvents() {
      return getEventsMap();
    }
    /**
     * <code>map&lt;string, .poset.proto.RoundEvent&gt; Events = 1;</code>
     */

    public java.util.Map<java.lang.String, poset.proto.PRoundInfo.RoundEvent> getEventsMap() {
      return internalGetEvents().getMap();
    }
    /**
     * <code>map&lt;string, .poset.proto.RoundEvent&gt; Events = 1;</code>
     */

    public poset.proto.PRoundInfo.RoundEvent getEventsOrDefault(
        java.lang.String key,
        poset.proto.PRoundInfo.RoundEvent defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, poset.proto.PRoundInfo.RoundEvent> map =
          internalGetEvents().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, .poset.proto.RoundEvent&gt; Events = 1;</code>
     */

    public poset.proto.PRoundInfo.RoundEvent getEventsOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, poset.proto.PRoundInfo.RoundEvent> map =
          internalGetEvents().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (java.util.Map.Entry<java.lang.String, poset.proto.PRoundInfo.RoundEvent> entry
           : internalGetEvents().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, poset.proto.PRoundInfo.RoundEvent>
        events = EventsDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        output.writeMessage(1, events);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (java.util.Map.Entry<java.lang.String, poset.proto.PRoundInfo.RoundEvent> entry
           : internalGetEvents().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, poset.proto.PRoundInfo.RoundEvent>
        events = EventsDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, events);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof poset.proto.PRoundInfo.RoundInfoMessage)) {
        return super.equals(obj);
      }
      poset.proto.PRoundInfo.RoundInfoMessage other = (poset.proto.PRoundInfo.RoundInfoMessage) obj;

      boolean result = true;
      result = result && internalGetEvents().equals(
          other.internalGetEvents());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (!internalGetEvents().getMap().isEmpty()) {
        hash = (37 * hash) + EVENTS_FIELD_NUMBER;
        hash = (53 * hash) + internalGetEvents().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static poset.proto.PRoundInfo.RoundInfoMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static poset.proto.PRoundInfo.RoundInfoMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static poset.proto.PRoundInfo.RoundInfoMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static poset.proto.PRoundInfo.RoundInfoMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static poset.proto.PRoundInfo.RoundInfoMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static poset.proto.PRoundInfo.RoundInfoMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static poset.proto.PRoundInfo.RoundInfoMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static poset.proto.PRoundInfo.RoundInfoMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static poset.proto.PRoundInfo.RoundInfoMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static poset.proto.PRoundInfo.RoundInfoMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(poset.proto.PRoundInfo.RoundInfoMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code poset.proto.RoundInfoMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:poset.proto.RoundInfoMessage)
        poset.proto.PRoundInfo.RoundInfoMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return poset.proto.PRoundInfo.internal_static_poset_proto_RoundInfoMessage_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetEvents();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetMutableEvents();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return poset.proto.PRoundInfo.internal_static_poset_proto_RoundInfoMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                poset.proto.PRoundInfo.RoundInfoMessage.class, poset.proto.PRoundInfo.RoundInfoMessage.Builder.class);
      }

      // Construct using poset.proto.PRoundInfo.RoundInfoMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        internalGetMutableEvents().clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return poset.proto.PRoundInfo.internal_static_poset_proto_RoundInfoMessage_descriptor;
      }

      public poset.proto.PRoundInfo.RoundInfoMessage getDefaultInstanceForType() {
        return poset.proto.PRoundInfo.RoundInfoMessage.getDefaultInstance();
      }

      public poset.proto.PRoundInfo.RoundInfoMessage build() {
        poset.proto.PRoundInfo.RoundInfoMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public poset.proto.PRoundInfo.RoundInfoMessage buildPartial() {
        poset.proto.PRoundInfo.RoundInfoMessage result = new poset.proto.PRoundInfo.RoundInfoMessage(this);
        int from_bitField0_ = bitField0_;
        result.events_ = internalGetEvents();
        result.events_.makeImmutable();
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof poset.proto.PRoundInfo.RoundInfoMessage) {
          return mergeFrom((poset.proto.PRoundInfo.RoundInfoMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(poset.proto.PRoundInfo.RoundInfoMessage other) {
        if (other == poset.proto.PRoundInfo.RoundInfoMessage.getDefaultInstance()) return this;
        internalGetMutableEvents().mergeFrom(
            other.internalGetEvents());
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        poset.proto.PRoundInfo.RoundInfoMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (poset.proto.PRoundInfo.RoundInfoMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.MapField<
          java.lang.String, poset.proto.PRoundInfo.RoundEvent> events_;
      private com.google.protobuf.MapField<java.lang.String, poset.proto.PRoundInfo.RoundEvent>
      internalGetEvents() {
        if (events_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              EventsDefaultEntryHolder.defaultEntry);
        }
        return events_;
      }
      private com.google.protobuf.MapField<java.lang.String, poset.proto.PRoundInfo.RoundEvent>
      internalGetMutableEvents() {
        onChanged();;
        if (events_ == null) {
          events_ = com.google.protobuf.MapField.newMapField(
              EventsDefaultEntryHolder.defaultEntry);
        }
        if (!events_.isMutable()) {
          events_ = events_.copy();
        }
        return events_;
      }

      public int getEventsCount() {
        return internalGetEvents().getMap().size();
      }
      /**
       * <code>map&lt;string, .poset.proto.RoundEvent&gt; Events = 1;</code>
       */

      public boolean containsEvents(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetEvents().getMap().containsKey(key);
      }
      /**
       * Use {@link #getEventsMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, poset.proto.PRoundInfo.RoundEvent> getEvents() {
        return getEventsMap();
      }
      /**
       * <code>map&lt;string, .poset.proto.RoundEvent&gt; Events = 1;</code>
       */

      public java.util.Map<java.lang.String, poset.proto.PRoundInfo.RoundEvent> getEventsMap() {
        return internalGetEvents().getMap();
      }
      /**
       * <code>map&lt;string, .poset.proto.RoundEvent&gt; Events = 1;</code>
       */

      public poset.proto.PRoundInfo.RoundEvent getEventsOrDefault(
          java.lang.String key,
          poset.proto.PRoundInfo.RoundEvent defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, poset.proto.PRoundInfo.RoundEvent> map =
            internalGetEvents().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, .poset.proto.RoundEvent&gt; Events = 1;</code>
       */

      public poset.proto.PRoundInfo.RoundEvent getEventsOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, poset.proto.PRoundInfo.RoundEvent> map =
            internalGetEvents().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearEvents() {
        getMutableEvents().clear();
        return this;
      }
      /**
       * <code>map&lt;string, .poset.proto.RoundEvent&gt; Events = 1;</code>
       */

      public Builder removeEvents(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        getMutableEvents().remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, poset.proto.PRoundInfo.RoundEvent>
      getMutableEvents() {
        return internalGetMutableEvents().getMutableMap();
      }
      /**
       * <code>map&lt;string, .poset.proto.RoundEvent&gt; Events = 1;</code>
       */
      public Builder putEvents(
          java.lang.String key,
          poset.proto.PRoundInfo.RoundEvent value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        getMutableEvents().put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, .poset.proto.RoundEvent&gt; Events = 1;</code>
       */

      public Builder putAllEvents(
          java.util.Map<java.lang.String, poset.proto.PRoundInfo.RoundEvent> values) {
        getMutableEvents().putAll(values);
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:poset.proto.RoundInfoMessage)
    }

    // @@protoc_insertion_point(class_scope:poset.proto.RoundInfoMessage)
    private static final poset.proto.PRoundInfo.RoundInfoMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new poset.proto.PRoundInfo.RoundInfoMessage();
    }

    public static poset.proto.PRoundInfo.RoundInfoMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RoundInfoMessage>
        PARSER = new com.google.protobuf.AbstractParser<RoundInfoMessage>() {
      public RoundInfoMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new RoundInfoMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RoundInfoMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RoundInfoMessage> getParserForType() {
      return PARSER;
    }

    public poset.proto.PRoundInfo.RoundInfoMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_poset_proto_RoundEvent_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_poset_proto_RoundEvent_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_poset_proto_RoundInfoMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_poset_proto_RoundInfoMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_poset_proto_RoundInfoMessage_EventsEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_poset_proto_RoundInfoMessage_EventsEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033poset/proto/roundInfo.proto\022\013poset.pro" +
      "to\"V\n\nRoundEvent\022\021\n\tConsensus\030\001 \001(\010\022\017\n\007W" +
      "itness\030\002 \001(\010\022$\n\006Famous\030\003 \001(\0162\024.poset.pro" +
      "to.Trilean\"\225\001\n\020RoundInfoMessage\0229\n\006Event" +
      "s\030\001 \003(\0132).poset.proto.RoundInfoMessage.E" +
      "ventsEntry\032F\n\013EventsEntry\022\013\n\003key\030\001 \001(\t\022&" +
      "\n\005value\030\002 \001(\0132\027.poset.proto.RoundEvent:\002" +
      "8\001*-\n\007Trilean\022\r\n\tUNDEFINED\020\000\022\010\n\004TRUE\020\001\022\t" +
      "\n\005FALSE\020\002B\014B\nPRoundInfob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_poset_proto_RoundEvent_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_poset_proto_RoundEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_poset_proto_RoundEvent_descriptor,
        new java.lang.String[] { "Consensus", "Witness", "Famous", });
    internal_static_poset_proto_RoundInfoMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_poset_proto_RoundInfoMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_poset_proto_RoundInfoMessage_descriptor,
        new java.lang.String[] { "Events", });
    internal_static_poset_proto_RoundInfoMessage_EventsEntry_descriptor =
      internal_static_poset_proto_RoundInfoMessage_descriptor.getNestedTypes().get(0);
    internal_static_poset_proto_RoundInfoMessage_EventsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_poset_proto_RoundInfoMessage_EventsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
