// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc.proto

package internal

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)



