// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: peers/proto/peer.proto

package peers.proto;

public final class PPeer {
  private PPeer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PeerOrBuilder extends
      // @@protoc_insertion_point(interface_extends:peers.proto.Peer)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int64 ID = 1;</code>
     */
    long getID();

    /**
     * <code>optional string NetAddr = 2;</code>
     */
    java.lang.String getNetAddr();
    /**
     * <code>optional string NetAddr = 2;</code>
     */
    com.google.protobuf.ByteString
        getNetAddrBytes();

    /**
     * <code>optional string PubKeyHex = 3;</code>
     */
    java.lang.String getPubKeyHex();
    /**
     * <code>optional string PubKeyHex = 3;</code>
     */
    com.google.protobuf.ByteString
        getPubKeyHexBytes();
  }
  /**
   * Protobuf type {@code peers.proto.Peer}
   */
  public  static final class Peer extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:peers.proto.Peer)
      PeerOrBuilder {
    // Use Peer.newBuilder() to construct.
    private Peer(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Peer() {
      iD_ = 0L;
      netAddr_ = "";
      pubKeyHex_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Peer(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              iD_ = input.readInt64();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              netAddr_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              pubKeyHex_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return peers.proto.PPeer.internal_static_peers_proto_Peer_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return peers.proto.PPeer.internal_static_peers_proto_Peer_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              peers.proto.PPeer.Peer.class, peers.proto.PPeer.Peer.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private long iD_;
    /**
     * <code>optional int64 ID = 1;</code>
     */
    public long getID() {
      return iD_;
    }

    public static final int NETADDR_FIELD_NUMBER = 2;
    private volatile java.lang.Object netAddr_;
    /**
     * <code>optional string NetAddr = 2;</code>
     */
    public java.lang.String getNetAddr() {
      java.lang.Object ref = netAddr_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        netAddr_ = s;
        return s;
      }
    }
    /**
     * <code>optional string NetAddr = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNetAddrBytes() {
      java.lang.Object ref = netAddr_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        netAddr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PUBKEYHEX_FIELD_NUMBER = 3;
    private volatile java.lang.Object pubKeyHex_;
    /**
     * <code>optional string PubKeyHex = 3;</code>
     */
    public java.lang.String getPubKeyHex() {
      java.lang.Object ref = pubKeyHex_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        pubKeyHex_ = s;
        return s;
      }
    }
    /**
     * <code>optional string PubKeyHex = 3;</code>
     */
    public com.google.protobuf.ByteString
        getPubKeyHexBytes() {
      java.lang.Object ref = pubKeyHex_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pubKeyHex_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (iD_ != 0L) {
        output.writeInt64(1, iD_);
      }
      if (!getNetAddrBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, netAddr_);
      }
      if (!getPubKeyHexBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, pubKeyHex_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (iD_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, iD_);
      }
      if (!getNetAddrBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, netAddr_);
      }
      if (!getPubKeyHexBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, pubKeyHex_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof peers.proto.PPeer.Peer)) {
        return super.equals(obj);
      }
      peers.proto.PPeer.Peer other = (peers.proto.PPeer.Peer) obj;

      boolean result = true;
      result = result && (getID()
          == other.getID());
      result = result && getNetAddr()
          .equals(other.getNetAddr());
      result = result && getPubKeyHex()
          .equals(other.getPubKeyHex());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getID());
      hash = (37 * hash) + NETADDR_FIELD_NUMBER;
      hash = (53 * hash) + getNetAddr().hashCode();
      hash = (37 * hash) + PUBKEYHEX_FIELD_NUMBER;
      hash = (53 * hash) + getPubKeyHex().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static peers.proto.PPeer.Peer parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static peers.proto.PPeer.Peer parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static peers.proto.PPeer.Peer parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static peers.proto.PPeer.Peer parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static peers.proto.PPeer.Peer parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static peers.proto.PPeer.Peer parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static peers.proto.PPeer.Peer parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static peers.proto.PPeer.Peer parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static peers.proto.PPeer.Peer parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static peers.proto.PPeer.Peer parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(peers.proto.PPeer.Peer prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code peers.proto.Peer}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:peers.proto.Peer)
        peers.proto.PPeer.PeerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return peers.proto.PPeer.internal_static_peers_proto_Peer_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return peers.proto.PPeer.internal_static_peers_proto_Peer_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                peers.proto.PPeer.Peer.class, peers.proto.PPeer.Peer.Builder.class);
      }

      // Construct using peers.proto.PPeer.Peer.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        iD_ = 0L;

        netAddr_ = "";

        pubKeyHex_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return peers.proto.PPeer.internal_static_peers_proto_Peer_descriptor;
      }

      public peers.proto.PPeer.Peer getDefaultInstanceForType() {
        return peers.proto.PPeer.Peer.getDefaultInstance();
      }

      public peers.proto.PPeer.Peer build() {
        peers.proto.PPeer.Peer result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public peers.proto.PPeer.Peer buildPartial() {
        peers.proto.PPeer.Peer result = new peers.proto.PPeer.Peer(this);
        result.iD_ = iD_;
        result.netAddr_ = netAddr_;
        result.pubKeyHex_ = pubKeyHex_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof peers.proto.PPeer.Peer) {
          return mergeFrom((peers.proto.PPeer.Peer)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(peers.proto.PPeer.Peer other) {
        if (other == peers.proto.PPeer.Peer.getDefaultInstance()) return this;
        if (other.getID() != 0L) {
          setID(other.getID());
        }
        if (!other.getNetAddr().isEmpty()) {
          netAddr_ = other.netAddr_;
          onChanged();
        }
        if (!other.getPubKeyHex().isEmpty()) {
          pubKeyHex_ = other.pubKeyHex_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        peers.proto.PPeer.Peer parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (peers.proto.PPeer.Peer) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long iD_ ;
      /**
       * <code>optional int64 ID = 1;</code>
       */
      public long getID() {
        return iD_;
      }
      /**
       * <code>optional int64 ID = 1;</code>
       */
      public Builder setID(long value) {
        
        iD_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 ID = 1;</code>
       */
      public Builder clearID() {
        
        iD_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object netAddr_ = "";
      /**
       * <code>optional string NetAddr = 2;</code>
       */
      public java.lang.String getNetAddr() {
        java.lang.Object ref = netAddr_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          netAddr_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string NetAddr = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNetAddrBytes() {
        java.lang.Object ref = netAddr_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          netAddr_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string NetAddr = 2;</code>
       */
      public Builder setNetAddr(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        netAddr_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string NetAddr = 2;</code>
       */
      public Builder clearNetAddr() {
        
        netAddr_ = getDefaultInstance().getNetAddr();
        onChanged();
        return this;
      }
      /**
       * <code>optional string NetAddr = 2;</code>
       */
      public Builder setNetAddrBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        netAddr_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object pubKeyHex_ = "";
      /**
       * <code>optional string PubKeyHex = 3;</code>
       */
      public java.lang.String getPubKeyHex() {
        java.lang.Object ref = pubKeyHex_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          pubKeyHex_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string PubKeyHex = 3;</code>
       */
      public com.google.protobuf.ByteString
          getPubKeyHexBytes() {
        java.lang.Object ref = pubKeyHex_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          pubKeyHex_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string PubKeyHex = 3;</code>
       */
      public Builder setPubKeyHex(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        pubKeyHex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string PubKeyHex = 3;</code>
       */
      public Builder clearPubKeyHex() {
        
        pubKeyHex_ = getDefaultInstance().getPubKeyHex();
        onChanged();
        return this;
      }
      /**
       * <code>optional string PubKeyHex = 3;</code>
       */
      public Builder setPubKeyHexBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        pubKeyHex_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:peers.proto.Peer)
    }

    // @@protoc_insertion_point(class_scope:peers.proto.Peer)
    private static final peers.proto.PPeer.Peer DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new peers.proto.PPeer.Peer();
    }

    public static peers.proto.PPeer.Peer getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Peer>
        PARSER = new com.google.protobuf.AbstractParser<Peer>() {
      public Peer parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Peer(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Peer> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Peer> getParserForType() {
      return PARSER;
    }

    public peers.proto.PPeer.Peer getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_peers_proto_Peer_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_peers_proto_Peer_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026peers/proto/peer.proto\022\013peers.proto\"6\n" +
      "\004Peer\022\n\n\002ID\030\001 \001(\003\022\017\n\007NetAddr\030\002 \001(\t\022\021\n\tPu" +
      "bKeyHex\030\003 \001(\tB\007B\005PPeerb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_peers_proto_Peer_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_peers_proto_Peer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_peers_proto_Peer_descriptor,
        new java.lang.String[] { "ID", "NetAddr", "PubKeyHex", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
